# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/vivado-works/FPGA_music/FPGA_music.srcs/sources_1/ip/SuperMusic/SuperMusic.xci
# IP: The module: 'SuperMusic' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado-works/FPGA_music/FPGA_music.srcs/sources_1/ip/SuperMusic/SuperMusic_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SuperMusic'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/vivado-works/FPGA_music/FPGA_music.srcs/sources_1/ip/SuperMusic/SuperMusic.xci
# IP: The module: 'SuperMusic' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado-works/FPGA_music/FPGA_music.srcs/sources_1/ip/SuperMusic/SuperMusic_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SuperMusic'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
